<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="2.88.9" />
    <PackageReference Include="SkiaSharp.NativeAssets.macOS" Version="2.88.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Elementary.VerseOfTheDay\Elementary.VerseOfTheDay.csproj" />
  </ItemGroup>

</Project>
